// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DisplayItem = { id: bigint, amount: bigint, image_path: string, display_name: string, };
